"""sync_schema_with_models

Revision ID: 8200c256dc0a
Revises: add_fast_hash
Create Date: 2026-02-15 19:52:59.016106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8200c256dc0a'
down_revision: Union[str, Sequence[str], None] = 'add_fast_hash'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_api_keys_active'), table_name='api_keys', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('idx_api_keys_project'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_fast_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_fast_hash'), 'api_keys', ['fast_hash'], unique=True)
    op.drop_index(op.f('idx_audit_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_project'), table_name='audit_logs')
    op.drop_index(op.f('idx_browser_tokens_expiry'), table_name='browser_tokens')
    op.drop_index(op.f('idx_browser_tokens_hash'), table_name='browser_tokens')
    op.drop_index(op.f('idx_browser_tokens_project'), table_name='browser_tokens')
    op.drop_index(op.f('idx_browser_tokens_revoked'), table_name='browser_tokens', postgresql_where='(revoked_at IS NOT NULL)')
    op.alter_column('cache', 'cache_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cache', 'cache_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_cache_expiry'), table_name='cache')
    op.drop_index(op.f('idx_cache_lookup'), table_name='cache')
    op.drop_index(op.f('idx_chunks_project'), table_name='chunks')
    op.drop_index(op.f('idx_chunks_project_tsv'), table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('idx_chunks_source'), table_name='chunks')
    op.create_index(op.f('ix_chunks_source_id'), 'chunks', ['source_id'], unique=False)
    op.drop_index(op.f('idx_conv_project'), table_name='conversations')
    op.drop_index(op.f('idx_conv_session'), table_name='conversations')
    op.drop_index(op.f('idx_embeddings_hnsw'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_embeddings_project'), table_name='embeddings')
    op.drop_index(op.f('idx_messages_conv'), table_name='messages')
    op.drop_index(op.f('idx_projects_active'), table_name='projects', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_projects_owner'), table_name='projects')
    op.alter_column('rate_limits', 'window_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_retrieval_metrics_performance'), table_name='retrieval_metrics')
    op.drop_index(op.f('idx_retrieval_metrics_project_time'), table_name='retrieval_metrics')
    op.drop_index(op.f('idx_sources_project'), table_name='sources')
    op.drop_index(op.f('idx_sources_status'), table_name='sources')
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.alter_column('user_usage', 'tokens_used',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_usage', 'requests_used',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'plan',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'free'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plan',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'free'::text"))
    op.alter_column('user_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_usage', 'requests_used',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_usage', 'tokens_used',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.create_index(op.f('idx_sources_status'), 'sources', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_sources_project'), 'sources', ['project_id'], unique=False)
    op.create_index(op.f('idx_retrieval_metrics_project_time'), 'retrieval_metrics', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_retrieval_metrics_performance'), 'retrieval_metrics', ['retrieval_time_ms'], unique=False)
    op.alter_column('rate_limits', 'window_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_projects_owner'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('idx_projects_active'), 'projects', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_messages_conv'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_embeddings_project'), 'embeddings', ['project_id'], unique=False)
    op.create_index(op.f('idx_embeddings_hnsw'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_conv_session'), 'conversations', ['project_id', 'session_id'], unique=False)
    op.create_index(op.f('idx_conv_project'), 'conversations', ['project_id'], unique=False)
    op.drop_index(op.f('ix_chunks_source_id'), table_name='chunks')
    op.create_index(op.f('idx_chunks_source'), 'chunks', ['source_id'], unique=False)
    op.create_index(op.f('idx_chunks_project_tsv'), 'chunks', ['project_id', 'search_tsvector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chunks_project'), 'chunks', ['project_id'], unique=False)
    op.create_index(op.f('idx_cache_lookup'), 'cache', ['project_id', 'cache_key', 'cache_type'], unique=False)
    op.create_index(op.f('idx_cache_expiry'), 'cache', ['expires_at'], unique=False)
    op.alter_column('cache', 'cache_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cache', 'cache_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_browser_tokens_revoked'), 'browser_tokens', ['revoked_at'], unique=False, postgresql_where='(revoked_at IS NOT NULL)')
    op.create_index(op.f('idx_browser_tokens_project'), 'browser_tokens', ['project_id'], unique=False)
    op.create_index(op.f('idx_browser_tokens_hash'), 'browser_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('idx_browser_tokens_expiry'), 'browser_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('idx_audit_project'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('idx_audit_created'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_logs', ['project_id', 'action'], unique=False)
    op.drop_index(op.f('ix_api_keys_fast_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_fast_hash'), 'api_keys', ['fast_hash'], unique=False)
    op.create_index(op.f('idx_api_keys_project'), 'api_keys', ['project_id'], unique=False)
    op.create_index(op.f('idx_api_keys_active'), 'api_keys', ['project_id'], unique=False, postgresql_where='(revoked_at IS NULL)')
    # ### end Alembic commands ###
