"""add fast_hash to api_keys

Revision ID: add_fast_hash
Revises: 7a2c8b1e9f0c
Create Date: 2026-02-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_fast_hash'
down_revision = '7a2c8b1e9f0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('fast_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_api_keys_fast_hash'), 'api_keys', ['fast_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_fast_hash'), table_name='api_keys')
    op.drop_column('api_keys', 'fast_hash')
    # ### end Alembic commands ###
