"""restore_indexes

Revision ID: 1fb143392d63
Revises: 8200c256dc0a
Create Date: 2026-02-15 19:57:41.532644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fb143392d63"
down_revision: Union[str, Sequence[str], None] = "8200c256dc0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_api_keys_active",
        "api_keys",
        ["project_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index("idx_api_keys_project", "api_keys", ["project_id"], unique=False)
    op.create_index(
        "idx_audit_action", "audit_logs", ["project_id", "action"], unique=False
    )
    op.create_index("idx_audit_created", "audit_logs", ["created_at"], unique=False)
    op.create_index("idx_audit_project", "audit_logs", ["project_id"], unique=False)
    op.create_index(
        "idx_browser_tokens_expiry", "browser_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_browser_tokens_hash", "browser_tokens", ["token_hash"], unique=False
    )
    op.create_index(
        "idx_browser_tokens_project", "browser_tokens", ["project_id"], unique=False
    )
    op.create_index(
        "idx_browser_tokens_revoked",
        "browser_tokens",
        ["revoked_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NOT NULL"),
    )
    op.create_index("idx_cache_expiry", "cache", ["expires_at"], unique=False)
    op.create_index(
        "idx_cache_lookup",
        "cache",
        ["project_id", "cache_key", "cache_type"],
        unique=False,
    )
    op.drop_index(op.f("ix_chunks_source_id"), table_name="chunks")
    op.create_index("idx_chunks_project", "chunks", ["project_id"], unique=False)
    op.create_index(
        "idx_chunks_project_tsv",
        "chunks",
        ["project_id", "search_tsvector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_chunks_source", "chunks", ["source_id"], unique=False)
    op.create_index("idx_conv_project", "conversations", ["project_id"], unique=False)
    op.create_index(
        "idx_conv_session", "conversations", ["project_id", "session_id"], unique=False
    )
    op.create_index(
        "idx_embeddings_hnsw",
        "embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "idx_embeddings_project", "embeddings", ["project_id"], unique=False
    )
    op.create_index("idx_messages_conv", "messages", ["conversation_id"], unique=False)
    op.create_index(
        "idx_projects_active",
        "projects",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index("idx_projects_owner", "projects", ["owner_id"], unique=False)
    op.create_index(
        "idx_retrieval_metrics_performance",
        "retrieval_metrics",
        ["retrieval_time_ms"],
        unique=False,
    )
    op.create_index(
        "idx_retrieval_metrics_project_time",
        "retrieval_metrics",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index("idx_sources_project", "sources", ["project_id"], unique=False)
    op.create_index(
        "idx_sources_status", "sources", ["project_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sources_status", table_name="sources")
    op.drop_index("idx_sources_project", table_name="sources")
    op.drop_index("idx_retrieval_metrics_project_time", table_name="retrieval_metrics")
    op.drop_index("idx_retrieval_metrics_performance", table_name="retrieval_metrics")
    op.drop_index("idx_projects_owner", table_name="projects")
    op.drop_index(
        "idx_projects_active",
        table_name="projects",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index("idx_messages_conv", table_name="messages")
    op.drop_index("idx_embeddings_project", table_name="embeddings")
    op.drop_index(
        "idx_embeddings_hnsw",
        table_name="embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("idx_conv_session", table_name="conversations")
    op.drop_index("idx_conv_project", table_name="conversations")
    op.drop_index("idx_chunks_source", table_name="chunks")
    op.drop_index("idx_chunks_project_tsv", table_name="chunks", postgresql_using="gin")
    op.drop_index("idx_chunks_project", table_name="chunks")
    op.create_index(op.f("ix_chunks_source_id"), "chunks", ["source_id"], unique=False)
    op.drop_index("idx_cache_lookup", table_name="cache")
    op.drop_index("idx_cache_expiry", table_name="cache")
    op.drop_index(
        "idx_browser_tokens_revoked",
        table_name="browser_tokens",
        postgresql_where=sa.text("revoked_at IS NOT NULL"),
    )
    op.drop_index("idx_browser_tokens_project", table_name="browser_tokens")
    op.drop_index("idx_browser_tokens_hash", table_name="browser_tokens")
    op.drop_index("idx_browser_tokens_expiry", table_name="browser_tokens")
    op.drop_index("idx_audit_project", table_name="audit_logs")
    op.drop_index("idx_audit_created", table_name="audit_logs")
    op.drop_index("idx_audit_action", table_name="audit_logs")
    op.drop_index("idx_api_keys_project", table_name="api_keys")
    op.drop_index(
        "idx_api_keys_active",
        table_name="api_keys",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # ### end Alembic commands ###
